language: python
python:
#  - "2.5"
  - "2.6"
  - "2.7"
  - "pypy-5.4"
#  - "3.0"
#  - "3.1"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy3"
sudo: false
install:
  - pip install coveralls
  - pip install protobuf
script:
  - make -C tools/python test
  - |
        if [ "$TRAVIS_PYTHON_VERSION" = "2.7" ]; then
           cd python
           COVERAGE_FILE=main.cov coverage run --source=phonenumbers ./testwrapper.py
           COVERAGE_FILE=pb2.cov coverage run --source=phonenumbers.pb2 ./testpb2.py
           coverage combine main.cov pb2.cov
           cd ..
        fi
after_success:
  - cd python && coveralls && cd ..
